steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/web.Dockerfile
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
