import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { AuthPortal } from "@/components/auth/AuthPortal";
export const AuthPage = ({ users, locations, departments, sessionUser, loading, onLogin, onSignup }) => (_jsxs("div", { className: "min-h-screen overflow-hidden bg-[linear-gradient(160deg,_#071221_0%,_#0c1f36_40%,_#15314a_100%)] text-white", children: [_jsx("div", { className: "pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.22),_transparent_24%),_radial-gradient(circle_at_bottom_right,_rgba(251,191,36,0.14),_transparent_20%)]" }), _jsxs("div", { className: "relative mx-auto flex min-h-screen max-w-[1440px] flex-col px-5 py-6 lg:px-8", children: [_jsxs("header", { className: "flex flex-wrap items-center justify-between gap-4 rounded-full border border-white/10 bg-white/6 px-4 py-3 backdrop-blur", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-3", children: [_jsx("img", { src: "/logo.jpg", alt: "SOS logo", className: "h-10 w-10 rounded-2xl object-cover ring-1 ring-white/10" }), _jsxs("div", { children: [_jsx("p", { className: "font-['Sora'] text-base font-semibold", children: "SOS ProcureSphere 360" }), _jsx("p", { className: "text-xs uppercase tracking-[0.24em] text-slate-300/70", children: "Secure access and identity orchestration" })] })] }), _jsx(Link, { to: "/", className: "inline-flex items-center justify-center rounded-full border border-white/12 bg-white/8 px-4 py-2 text-sm font-medium text-white transition hover:bg-white/14", children: "Back to landing page" })] }), _jsxs("div", { className: "grid flex-1 items-center gap-8 py-10 lg:grid-cols-[0.9fr_1.1fr] lg:py-12", children: [_jsxs("section", { className: "max-w-2xl", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.34em] text-cyan-200/85", children: "Identity and access" }), _jsx("h1", { className: "mt-5 max-w-xl font-['Sora'] text-4xl font-semibold leading-tight text-white sm:text-5xl", children: "Sign in with a polished, role-aware entry point built for a serious operations platform." }), _jsx("p", { className: "mt-5 max-w-xl text-base leading-8 text-slate-200/82", children: "Procurement, finance, warehouse, and audit teams need a clear front door. This access flow supports secure sign-in, rapid demo entry, and new requester provisioning without sending users into an unfinished prototype state." }), _jsx("div", { className: "mt-8 grid gap-4 sm:grid-cols-3", children: [
                                        {
                                            label: "Role-based entry",
                                            value: "RBAC"
                                        },
                                        {
                                            label: "Two-factor path",
                                            value: "TOTP"
                                        },
                                        {
                                            label: "Session traceability",
                                            value: "Audit log"
                                        }
                                    ].map((item) => (_jsxs("div", { className: "rounded-[26px] border border-white/10 bg-white/6 p-5 backdrop-blur", children: [_jsx("p", { className: "font-['Sora'] text-2xl font-semibold text-white", children: item.value }), _jsx("p", { className: "mt-2 text-sm text-slate-300/78", children: item.label })] }, item.label))) }), _jsx("div", { className: "mt-8 rounded-[28px] border border-white/10 bg-slate-950/30 p-5 text-sm leading-7 text-slate-300/82", children: "Production deployment can be wired to SSO, SAML, OIDC, enforced TOTP, and device controls. The current pilot keeps the interface production-shaped while the backend remains easy to demonstrate and extend." })] }), _jsx("section", { children: _jsx(AuthPortal, { users: users, locations: locations, departments: departments, sessionUser: sessionUser, loading: loading, onLogin: onLogin, onSignup: onSignup, title: "Sign in or provision a requester account", subtitle: "Use a work email to enter the platform, or create a programme requester profile for requisition and document workflows." }) })] })] })] }));
